### ISSUE TITLE
Warnings and errors

### ISSUE THREAD

**Issue by xenonshop** [adrianb11/directadmin_rclone_backup#10]
After install I'm getting: Warning: scandir(/usr/local/directadmin/plugins/rclone_backup/admin/elements/conf/active): failed to open dir: No such file or directory in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: scandir(): (errno 2): No such file or directory in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: array_diff(): Argument #1 is not an array in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: scandir(/usr/local/directadmin/plugins/rclone_backup/admin/elements/conf/inactive): failed to open dir: No such file or directory in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: scandir(): (errno 2): No such file or directory in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: array_diff(): Argument #1 is not an array in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: scandir(/usr/local/directadmin/plugins/rclone_backup/admin/elements/conf/pending): failed to open dir: No such file or directory in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: scandir(): (errno 2): No such file or directory in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51 Warning: array_diff(): Argument #1 is not an array in /usr/local/directadmin/plugins/rclone_backup/admin/elements/functions.php on line 51

Also I cannot create a cronjbo, it reloads the page continously. Maybe  because I manually installed the plugin, I didn't know other ways.

**Comment by adrianb11** [comment]
This has been resolved in version 1.0.5. Issue was required folders not being created.
