### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by DrMxrcy** [adrianb11/directadmin_rclone_backup#14]
Hi. I have Rclone and a Config already

I am getting the error with the plugin

plugin.tar.gz extracted
install.sh returned a non-zero value: 
Error with install script

**Comment by DrMxrcy** [comment]
Error Log
2022:01:21-16:10:59: (1)Execle error on /usr/local/directadmin/plugins/rclone_backup/scripts/install.sh : No such file or directory

**Comment by xenonshop** [comment]
same here

**Comment by adrianb11** [comment]
Thank you for pointing this out.  The issue which was due to CRLF instead of LF should now be fixed in 1.0.6.

**Comment by DrMxrcy** [comment]
Cool! Will try it out!

**Comment by DrMxrcy** [comment]
The Install worked, But there is now an error on the CronJob Page
![b3b02ebc-1161-4875-9e81-44b6259dd349](https://user-images.githubusercontent.com/58747968/150691381-194fb0d8-7043-4557-a23d-6af3b974aaeb.png)

Page Keeps Refreshing

**Comment by adrianb11** [comment]
Do you have any domains setup under the admin account or are these setup under new accounts.

What's the output of this (replace IP address) - https://SERVER IP:2222/CMD_API_DOMAIN?json=yes&action=document_root

**Comment by DrMxrcy** [comment]
I have domains under the admin account

{
	"users": 
	{
		"admin": 
		{
			"domains": 
			{
				"example1.com": 
				{
					"private_html": "/home/admin/domains/example1.com/private_html",
					"public_html": "/home/admin/domains/example1.com/public_html",
					"subdomains": 
					{
					}
				},
				"example2.com": 
				{
					"private_html": "/home/admin/domains/example2.net/private_html",
					"public_html": "/home/admin/domains/example2.net/public_html",
					"subdomains": 
					{
					}
				}
			}
		}
	}
}

**Comment by adrianb11** [comment]
Does adding `var_dump($domainJSON); die;` on line 29 give the same output?

/usr/local/directadmin/plugins/rclone_backup/admin/elements/pages/create.php

string(1234) "{ "users": { "admin": { "domains": { "DOMAIN.com": { "private_html": "/home/admin/domains/DOMAIN

**Comment by DrMxrcy** [comment]
Now get an error in the ui "string(70) "use https:string(70) "use http"

Same output at  https://SERVER IP:2222/CMD_API_DOMAIN?json=yes&action=document_root

**Comment by adrianb11** [comment]
Sorry I don't understand that message.  Can you post the full output please (with domains redacted).

Is there any log entries referencing this?

Do you use HTTP or HTTPS for admin?

**Comment by adrianb11** [comment]
Installing the version below should product a similar output to the image below.  Please confirm this is the case.
[rclone_backup.tar.gz](https://github.com/adrianb11/directadmin_rclone_backup/files/7925505/rclone_backup.tar.gz)
![Capture](https://user-images.githubusercontent.com/77499644/150783136-b1729c84-75c4-4bb1-bce3-81e0052b597a.PNG)

**Comment by db25i** [comment]
I get the same error as above
I installed the above attached file
Related error screenshots: https://s4.ax1x.com/2022/02/01/HkBAhQ.png

**Comment by awab228** [comment]
i have the same issue as the post above, after installing the custom version made by you above , any hopes that this might be fixed soon ?

**Comment by adrianb11** [comment]
Progress has been made.  Now need to add changes and test.

**Comment by adrianb11** [comment]
Version 1.0.7 has now been published.
